### ISSUE TITLE
Lost reference to publisher camera

### ISSUE THREAD

**Issue by Carlosp16** [opentok/opentok-react-native#150] opened 2018-08-09 18:14 UTC
After a time using the app in background or sometimes after a reconnect the publisher loss the reference to the camera. The audio still work for the publisher but the video is lost(Black screen). We don't received any errors in console. Any ideas to fix it?

**Comment by msach22** [comment] 2018-08-13 21:02
@Carlosp16 This seems like a duplicate of the following: https://github.com/opentok/opentok-react-native/issues/141

Could you please check out the solution mentioned in the issue?

**Comment by evillemez** [comment] 2018-08-14 18:34
I think this is distinct from #141

We have an issue that is somewhat difficult to reproduce where a user may put the app in the background for some time, then restore the app to foreground, but their video is gone.  It doesn't happen every time, sometimes the video comes back as expected.  When it does disappear, toggling the video on/off doesn't have any effect - both users just see a black feed.

I should note that it's not *only* moving the app to the background.  This happens occasionally while the users are in a session - but it has seemed to happen more frequently in the cases where one user leaves the app, then returns.

We've focused primarily on iOS - not sure about behavior on Android.

**Comment by cmedinadeveloper** [comment] 2018-08-17 15:07
@msach22 Ticket #141 is not related to this issue, because I have "Background Mode" capability activated on Xcode. While you are on a call and App goes into background mode the session is not being destroyed, the real problem is when the App comes into foreground again, for some reason the publisher video feed is gone (black screen), I tried forcing the publisher component to render again based on the AppState(Active, Inactive, Background) but no luck, once the app goes to background you lose the publisher video feed.

**Comment by evillemez** [comment] 2018-08-30 17:47
@msach22 Any pointers on where we could look?  Still haven't been able to figure this one out...

**Comment by msach22** [comment] 2018-09-03 02:12
@evillemez @cmedinadeveloper Apologies for the delay on this, will check this out and report my findings in the next few days!

**Comment by evillemez** [comment] 2018-09-17 16:42
@msach22 Hey, just checking in.  Did you have any luck uncovering anything related to this?  If there's any information we can provide, or something you would like us to try - please let us know and we'll do what we can.

**Comment by msach22** [comment] 2018-09-19 15:54
@evillemez Could you please email me at manik@tokbox.com with a recent sessionId where this happens? 
This will allow me to see if you are still sending video packets or not. I'm trying to see if the camera gets reclaimed but somehow it doesn't bubble up to the RN view.

You can also use [Inspector](https://tokbox.com/developer/tools/inspector/) to check out the video packets information

**Comment by evillemez** [comment] 2018-09-19 17:45
@msach22 Yeah - we can create a session to reproduce and reach out to you over email. Thanks so much!

**Comment by msach22** [comment] 2018-09-19 18:10
@evillemez Awesome, looking forward to it!

**Comment by devsujith** [comment] 2018-09-28 12:44
Any luck with this issue? Im facing the same one in SWIFT SDK for opentok. The publisher feed goes black sometimes when the app comes back to foreground.

**Comment by cmedinadeveloper** [comment] 2018-09-28 13:41
@devsujith No luck, this is still happening to us, we are not able to find a workaround

**Comment by devsujith** [comment] 2018-09-28 14:57
Are you facing this issue each time the app is backgrounded and comes back to foreground? Or is it the scenario when the session window is reconnected once and then followed by background and resume?

**Comment by evillemez** [comment] 2018-10-29 14:38
Just a note that, for us, this seems to be an iOS only issue.  On Android the video continues if the app is in the background.  So switching back and forth doesn't seem to cause a problem.

**Comment by msach22** [comment] 2018-11-12 16:47
@evillemez Yes, if you unmount and remount a publisher component, you will essentially remove the old publisher and create a new publisher.

**Comment by mmubasher** [comment] 2018-11-30 18:05
@evillemez Is there a way to detect if video is lost. On android if camera is taken away by any other app like whatsapp video call, video stream freezes for me too

**Comment by msach22** [comment] 2018-12-11 19:08
@evillemez Have you tried using `AppState` and unmounting and remounting the `OTPublisher` component?

If you can see that the publisher changed from background mode to foreground and they are not sending any videoNetworkStats, you can unmount and remount to create a new publisher instance

One more question, is this happening on all iOS devices or just specific ones?

**Comment by evillemez** [comment] 2019-05-05 01:33
For what it's worth, I'm still having this issue on iOS in the latest version, but I also still haven't been able to figure out a consistent way to reproduce it.

What I do know is that when this does happen the remote side still thinks the received stream has video.

**Comment by Rjayone** [comment] 2019-05-05 10:43
@evillemez 
I resolved my issue with black frames. The last steps i've made is add didDrop sampleBuffer: and reconfigure session with another preset.

https://paste.ofcode.org/VhwY9YEmnxqEqFbkepSb2N
CameraController - the object that configure and manages AVCaptureSession

**Comment by nagenderpratapqss** [comment] 2019-05-28 06:21
@Rjayone - Link is broken. Can you share it again.

@msach22 - This issue is still happening. Checking on iPhone and iPad - iOS version- 12.1.4 - XCode 10.2. Any updates for the resolution?

@evillemez - Have you figured out any solution on this?

**Comment by evillemez** [comment] 2019-06-04 15:21
@nagenderpratapqss We still don't have a solution, but we also still can't reliably reproduce the problem.  It's odd, when it does happen, it happens consistently, but I still don't know what the initial trigger is.

**Comment by ggoldens** [comment] 2019-08-05 14:01
@evillemez Have you check if this issue happens also in a native iOS app using the latest Opentok SDK? Just wondering if it's related to opentok-react-native or it's a bug on the iOS SDK.

**Comment by evillemez** [comment] 2019-08-09 18:29
@ggoldens I haven't tried this in a native iOS app, so I'm not sure.

We have seen (very rare) cases of this happening on Android also... but it was a while ago, with older versions of the lib, on old Android devices with other issues, so I'm honestly not sure it's relevant.

I wish I could reproduce this issue consistently, but still no luck.

**Comment by Rjayone** [comment] 2019-09-05 15:33
There is a code i used

[CaptureSettings.swift.zip](https://github.com/opentok/opentok-react-native/files/3580027/CaptureSettings.swift.zip)

**Comment by slauzinho** [comment] 2020-06-02 15:50
@ggoldens This issue is still happening for me. 
I'm able to reproduce it every time if during a video call on my android phone I force stop the app, the other person will see a blank screen, and even if the original person tries to join the video session they too will see a blank screen.

This is with the latest opentok-react-native version

**Comment by hussainsherwani** [comment] 2021-06-24 06:54
@ggoldens This is not specific for ios , I am getting this issue on different Android devices  with latest sdk `0.17.2`

**Comment by mvarie** [comment] 2021-09-30 23:37
@evillemez Still happening with OpenTok SDK 2.20.1.

**Closed** 2023-11-07 10:25 UTC
Labels: bug
