### ISSUE TITLE
Zoom In and Zoom out for screen sharing in subscriber

### ISSUE THREAD

**Issue by menasSawwaf** [opentok/opentok-react-native#441] opened 2020-08-17 13:49 UTC
Is there way to zoom in and zoom out  for subscriber view when publisher start screen sharing?

**Comment by tusharpsychonline** [comment] 2020-12-22 17:29
Hello mesasSawwaf,

Were you able to get that resolved? I tried and I see cropped screenshare, only the middle section is visible.

**Comment by christophby** [comment] 2021-02-10 09:57
@menasSawwaf @tusharpsychonline did you fix it somehow?

**Comment by abdulajet** [comment] 2021-05-17 15:46
seems like a duplicate of #439

**Closed by abdulajet** 2021-05-17 15:46 UTC
Labels: duplicate
