### ISSUE TITLE
Pre-compiled headers don't get generated

### ISSUE THREAD

**Issue by smakosh** [opentok/opentok-react-native#247] opened 2019-03-08 20:38 UTC
I'm having issues with the pre-compiled headers which don't get generated with cocoapods,

Here's my Podfile:

```
platform :ios, '9.0'

target 'project_name' do

  pod 'OpenTok', '2.15.3'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'ART', #  react-native-progress
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'React'
      target.remove_from_project
    end
  end
end
```

As temporary solution, I drag & drop a previous generated OpenTok folder on both public/private folders located in `/pods/Headers/`.

I'm using the latest opentok react native library & the latest react-native.

**Comment by msach22** [comment] 2019-03-08 20:41
@smakosh Thanks for filing the issue - I believe this is a known issue and is related to using Cocoapods 1.6.0: https://github.com/opentok/opentok-react-native/issues/235

Could you confirm if you're using Cocoapods 1.6.0?

**Comment by smakosh** [comment] 2019-03-08 20:45
Yup, I confirm that

**Comment by msach22** [comment] 2019-03-08 20:56
Thanks for confirming - I'm going to go ahead and close this issue because it's a duplicate of #235. Please track issue #235 for progress

**Closed by msach22** 2019-03-08 20:56 UTC
