### ISSUE TITLE
Sudden connectionDestroyed event fired, but the video/audio was working fine both before and after the event fired

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#394] opened 2020-03-27 20:59 UTC
One of our users experienced a `connectionDestroyed` event in `OTSession`'s `eventHandlers` during an OpenTok session containing 2 users. However, users of both devices experienced a properly-working realtime video chat throughout the time both before and after the `connectionDestroyed` event fired. 

The session ID of this session is:
```
1_MX40NTgyODk0Mn5-MTU4NTMzOTQxMzQxM35oOEdoSEhSKytRYjhGUU1uV0djVit4RDl-fg
```

**Comment by evillemez** [comment] 2020-03-31 16:07
This sounds like the behavior we see in certain cases, so wondering if it could be a duplicate of #271  ?

Do you know if there could have been any case shortly before this occurred where the `OTSession` component was remounted?  If so, 271 might be the reason.

**Comment by sunweiyang** [comment] 2020-04-08 21:00
My codebase does not remount the `OTSession` component after initial instantiation. If it helps, this seems to happen more frequently for longer OpenTok sessions (greater than 30 minutes).

**Comment by Sach-SPF** [comment] 2020-04-15 21:53
Guys - Any solution on this one?

**Comment by adaerodriguez** [comment] 2020-04-22 07:13
Please, any change on this issue?

**Comment by HarshitPadalia** [comment] 2020-07-22 06:14
Any solution on this one I am also facing same issue with latest 0.14.0 version?

**Comment by TalhaAhsan** [comment] 2022-06-19 10:45
Are you still facing this issue?

**Comment by TalhaAhsan** [comment] 2022-07-18 17:23
Closing this issue as is stale now. If required, a new issue can be opened.

**Closed by TalhaAhsan** 2022-07-18 17:23 UTC
Labels: bug
