### ISSUE TITLE
RuntimeException: Illegal callback invocation from native module.

### ISSUE THREAD

**Issue by steverob** [opentok/opentok-react-native#144] opened 2018-07-24 04:04 UTC
@msach22 Ran into this native crash. Looks like some callback being fired onDisconnect. Any idea why this is crashing?

```
java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
    at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:28)
    at com.opentokreactnative.OTSessionManager.onDisconnected(OTSessionManager.java:482)
    at com.opentok.android.Session.onDisconnected(Session.java:1605)
    at com.opentok.android.Session$5.run(Session.java:1566)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by msach22** [comment] 2018-07-24 16:20
@steverob Can you share when this is happening? Any reproduction steps?

**Comment by msach22** [comment] 2018-07-31 16:05
@steverob Any updates on the reproduction steps?

**Comment by msach22** [comment] 2018-08-07 00:00
@steverob I'm closing this issue because it doesn't provide reproduction steps, but please feel free to re-open with reproduction steps as needed!

**Closed by msach22** 2018-08-07 00:00 UTC
