### ISSUE TITLE
Attempt to invoke virtual method 'void android.widget.FrameLayout.removeAllViews()' on a null object reference

### ISSUE THREAD

**Issue by renanpupin** [opentok/opentok-react-native#92] opened 2018-05-28 14:49 UTC
RN 0.51
OT RN 0.6.4

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.removeAllViews()' on a null object reference
    at com.opentokreactnative.OTSessionManager$2.run(OTSessionManager.java:281)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5343)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by msach22** [comment] 2018-05-29 15:31
@renanpupin Can you please share when this happens and additional details that can help me reproduce this?

**Comment by renanpupin** [comment] 2018-05-29 15:37
Looking at my logs, it is happening after my componentWillUnmount executes.

Not sure about how it is happening, because my error tracker got it from my production app. 
Anyway I will try to put more information here:

NullPointerExceptioncom.opentokreactnative.OTSessionManager$2 in run

Family | XT1033
-- | --
Model | XT1033 (LPBS23.13-56-2)
Architecture | armeabi-v7a
Battery Level | 82%
Orientation | portrait
Memory | Total: 888.8 MB / Free: 212.9 MB
Capacity | Total: 12.9 GB / Free: 7.8 GB
Simulator | false
brand | motorola
charging | false
low_memory | false
manufacturer | motorola
online | true
screen_density | 2
screen_dpi | 320
screen_resolution | 1184x720


Name | Android
-- | --
Version | 5.1 (LPBS23.13-56-2)
Kernel Version | Linux version 3.4.42-g89906d6(gcc version 4.8 (GCC) ) #1 SMP PREEMPT Fri Feb 26 07:13:58 CST 2016
Rooted | no

**Comment by msach22** [comment] 2018-05-29 15:38
Thanks @renanpupin! I will check this out and update you on my findings as well.

**Comment by msach22** [comment] 2018-05-29 23:55
@renanpupin I'm adding a null check before `removeAllViews` gets called. This should go out with the `0.6.5` release

**Comment by msach22** [comment] 2018-05-30 00:36
This is a duplicate of this: https://github.com/opentok/opentok-react-native/issues/85

Closing this issue

**Closed by msach22** 2018-05-30 00:36 UTC
