### ISSUE TITLE
The event.stream.hasAudio value in streamPropertyChanged does not change on Android

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#251] opened 2019-03-28 16:04 UTC
# Bug Report

**Current behavior**
The `sessionEventHandler` for `streamPropertyChanged`, specifically the `event.stream.hasAudio` value, does not change properly on Android. It does work fine on iOS.

I haven't had a chance to test the other `streamPropertyChanged` values yet; unsure if it's an indicator of a larger `streamPropertyChanged` issue.

**Steps to reproduce**
Set up an OpenTok component with a `constructor()` that contains the following:
```
  constructor(props) {
    super(props);
    this.sessionEventHandlers = {
      streamPropertyChanged: event => {
        if (event.stream.hasAudio) {
          console.log('Someone's publishing audio!')
        }
      }
    };
  }
```
Start an OpenTok session with all clients in the stream starting out without publishing audio. Then have one client start publishing audio.

Observe that if a client is iOS, it successfully displays the above `console.log()` in RN debugger when audio starts in the stream, but it doesn't happen if a client is Android.

**What is the current *bug* behavior?**
The streamPropertyChanged event.stream.hasAudio changes as expected on iOS, but not on Android.

**What is the expected *correct* behavior?**
The streamPropertyChanged event.stream.hasAudio should change on both iOS and Android.

**Comment by evillemez** [comment] 2019-04-09 20:29
Thanks for submitting this... I overlooked `streamPropertyChanged` because it's not in the docs.

Did you get any extra info on this after posting?  Like, does `changedProperty` and `oldValue` and `newValue` update as expected for you?  It seems like it's updating as expected for me in the Android simulators.

**Comment by msach22** [comment] 2019-04-09 22:44
@sunweiyang @evillemez I'm seeing this work for me. @sunweiyang Could you please share which native SDK version you're using on Android?

**Comment by evillemez** [comment] 2019-04-12 02:58
@sunweiyang @msach22 I just updated to `0.9.8`, and look to be having this issue now, or something similar at least.

I disable video on one side, and on the other side where I have connected to RNDebugger, I see `streamPropertyChanged` called with the following:

```js
{
  changedProperty: "hasVideo",
  newValue: false,
  oldValue: true,
  stream: {
    hasVideo: true,
    hasAudio: true
  }
}
```

The same is happening now for audio as well.  If I toggle the mute on the remote side to stop publishing audio, then on the local side I get:

```js
{
  changedProperty: "hasAudio",
  newValue: false,
  oldValue: true,
  stream: {
    hasVideo: true,
    hasAudio: true
  }
}
```

I can hack around this in the short term, but it's a noticeable behavior change... unfortunately the version I was previously testing against was `0.8.4`, so I can't comment on when the behavior may have changed.

**Comment by msach22** [comment] 2019-04-15 15:49
@sunweiyang @evillemez Thanks for sharing more details. There weren't any code changes for this feature so I'm thinking it's a native SDK issue. I'm going to run the latest OTRN version with 2.14.x and 2.15.x and see if I can reproduce the issue.

**Comment by msach22** [comment] 2019-05-10 21:39
Hi Folks, I ran this with the latest release (using native SDK 2.16.0) and I'm not seeing this issue. Could you folks please check on your end if you're seeing this?

**Comment by msach22** [comment] 2019-05-13 17:48
Hi folks, I'm following up on this. I've created a patch for https://github.com/opentok/opentok-react-native/issues/269 and will release that soon. Closing this issue, but please let me know if this exists with v0.10.x

**Closed by msach22** 2019-05-13 17:48 UTC
