### ISSUE TITLE
Android app with API level 29 crashes - Error while updating property 'streamId' of a view managed by OTSubscriberViewManager

### ISSUE THREAD

**Issue by vishnu-ramineni** [opentok/opentok-react-native#455] opened 2020-10-26 07:54 UTC
Android app details
opentok-react-native(v0.14.0)
```
        buildToolsVersion = "29.0.2"
        compileSdkVersion = 29
        targetSdkVersion = 29
```

<img width="399" alt="Screenshot 2020-10-26 at 1 20 39 PM" src="https://user-images.githubusercontent.com/63717306/97146791-7aebca00-178e-11eb-922a-1108c1a4dcd2.png">

**Comment by enricop89** [comment] 2020-10-26 09:53
Can you please add steps to reproduce?

**Comment by 0x1bitcrack3r** [comment] 2020-11-16 03:00
> Can you please add steps to reproduce?

the [fix](https://github.com/opentok/opentok-react-native/pull/456) has been made we can close this issue

**Comment by ggoldens** [comment] 2021-01-26 18:42
Closing this PR since the fix was released in 0.15.0.

**Closed by ggoldens** 2021-01-26 18:42 UTC

**Comment by vishalcodiant** [comment] 2021-08-31 05:09
it is again reopens this issue occurred to me in v0.18.0
![image](https://user-images.githubusercontent.com/73869553/131445458-7196a3ab-a773-4f66-b1b0-5a108674ba29.png)

**Comment by vishalcodiant** [comment] 2021-08-31 05:50
fixed https://github.com/opentok/opentok-react-native/pull/525
