### ISSUE TITLE
Subscribing to screen shared from web shows croped window not full in potrait mode

### ISSUE THREAD

**Issue by rahult-sdei** [opentok/opentok-react-native#560] opened 2022-01-06 09:59 UTC
Subscribing to screen shared from web shows croped window not full in potrait mode.
Any solution to get full window in mobile potratit mode

**Comment by enricop89** [comment] 2022-05-27 13:56
Can you provide more details please?

**Comment by TalhaAhsan** [comment] 2022-07-19 23:24
Seems like a duplicate of #439. Can you provide further information there?

**Closed by TalhaAhsan** 2022-07-19 23:24 UTC
Labels: question
