### ISSUE TITLE
Support to audio output route ear/speaker

### ISSUE THREAD

**Issue by renanpupin** [opentok/opentok-react-native#173] opened 2018-09-18 15:26 UTC
It will be nice if we have audioOutputRoute property explicit at OTSubscriber object.

`
<OTSubscriber audioOutputRoute={"ear"} />
`

or 

`
<OTSubscriber audioOutputRoute={"speaker"} />
`

**Comment by Carlosp16** [comment] 2018-10-11 22:47
For now you can use IncallManager library for that.

**Comment by daft300punk** [comment] 2019-04-28 16:00
Using InCallManager( https://www.npmjs.com/package/react-native-incall-manager) doesn't work for me. Anyone had any success with it? Is there any other way to route audio through the earpiece rather than the default speaker?

**Comment by renanpupin** [comment] 2019-04-28 18:21
Yeah, it does not work with OT.

**Comment by flogy** [comment] 2021-05-31 09:15
Would required this feature as well. Is there any update on this?

**Comment by enricop89** [comment] 2022-05-27 14:05
Duplicate of #159

**Closed by enricop89** 2022-05-27 14:05 UTC
Labels: API Proposal
