### ISSUE TITLE
Cannot change subscribeToAudio status once <OTSubscriber> is instantiated

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#124] opened 2018-06-29 00:10 UTC
After the views are rendered, changing the `subscribeToAudio` boolean through either `<OTSubscriber>`'s  `properties` or `streamProperties` props did not modify the audio subscription state.

We need to implement a "silence subscriber stream" toggle button while still allowing other sounds to play(sound effects, etc.), so dynamic `subscribeToAudio` is necessary. Is there currently any way to change `subscribeToAudio` once the view is instantiated? And if not, what is a recommended solution? This would be a great feature.

**Comment by msach22** [comment] 2018-07-02 15:37
@sunweiyang Hmm, I can't seem to reproduce this. I render the `OTSubscriber` component with the initial properties using the `properties` prop and if I want to modify a stream property, I use the `streamProperties` component as shown here:
https://github.com/opentok/opentok-react-native/blob/master/docs/OTSubscriber.md

Could you please share your implementation?

**Comment by msach22** [comment] 2018-07-02 20:36
@sunweiyang Awesome! Please let me know what changes we can make to make the documentation more clear. We're always looking for feedback to improve our offerings!

**Comment by sunweiyang** [comment] 2018-07-05 19:49
@msach22 Actually I am still unable to modify subscriber audio state using `streamProperties`. Are we still implementing it incorrectly?

To clarify, our subscriber works (both audio and video successfully subscribed and rendered), but we can't toggle the subscriber audio on/off.

Our constants for styles:
```
const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;
```

Our `constructor` (`this.subscriberEventHandlers` not shown but we have it defined):
```
...
    this.sessionEventHandlers = {
      streamCreated: event => {
        // Stream created
        const streamProperties = {
          ...this.state.streamProperties,
          [event.streamId]: {
            subscribeToAudio: true,
            subscribeToVideo: true,
            style: {
              width: windowWidth,
              height: windowHeight
            }
          }
        };
        this.setState({ streamProperties, streamId: event.streamId });
      },
    };
...
```

Our command for toggling subscriber mute (triggered by a `TouchableOpacity` in our UI):
```
...
  _handleMute() {
      var streamProperties = this.state.streamProperties;
      streamProperties[this.state.streamId].subscribeToAudio = this.state.muted;
      this.setState({
        streamProperties,
        muted: !this.state.muted
      });
  }
...
```

Our `OTSubscriber` component (contained within our `OTSession` component):
```
              ...
              <OTSubscriber
                properties={{
                  subscribeToAudio: true,
                  subscribeToVideo: true
                }}
                eventHandlers={this.subscriberEventHandlers}
                style={{
                  width: windowWidth,
                  height: windowHeight
                }}
                streamProperties={this.state.streamProperties}
              />
              ...
```

**Comment by mbouxin** [comment] 2018-07-07 11:39
When I first implemented this functionnality, I got a similar problem which was due to the fact that both my Publisher and Subscriber fired the streamCreated event (which is not the case for the javascript opentok API).

From what I read here, if you have a publisher, the streamId is not guaranteed to be the subscriber one.

My solution was to save the streamId of the publisher's streamCreated event to the state as a publishedStreamId variable and to filter out the session's streamCreated events if they were fired with this streamId

**Comment by sunweiyang** [comment] 2018-07-10 21:53
It's true that I have both a publisher and a subscriber during each session (and the publisher connects first). However, when I pipe my `this.state.streamProperties` to `console.log()`, I only see one `streamId` created. @mbouxin, are you suggesting that I should actually be seeing 2 `streamIds`?

If someone can provide a quick example for the recommended method of toggling subscriber's `subscribeToAudio`, that'd be fantastic.

**Comment by msach22** [comment] 2018-07-10 23:22
@sunweiyang Here's a quick sample on how to toggle audio using `subscribeToAudio` and `streamProperties` prop. 

```
import React, { Component } from 'react';
import { View, Button } from 'react-native';
import { OTSession, OTPublisher, OTSubscriber } from 'opentok-react-native';

export default class App extends Component {
  constructor(props) {
    super(props);
    this.apiKey = '';
    this.sessionId = '';
    this.token = '';
    this.state = {
      streamProperties: {},
    }
  }
  sessionEvents = {
    streamCreated: (event) => {
      const streamProperties = {...this.state.streamProperties, [event.streamId]: {
          subscribeToAudio: true,
          subscribeToVideo: true,
          style: {
            width: 200,
            height: 200,
          }
        }};
      this.setState({
        streamProperties,
      });
    },
  }
  
  render() {
    const allButtons = Object.keys(this.state.streamProperties).map((streamId) => {
      const currentStream = {
        ...this.state.streamProperties[streamId], 
        subscribeToAudio: !this.state.streamProperties[streamId].subscribeToAudio, 
      };
      const streamProperties = {...this.state.streamProperties, [streamId]: currentStream};
      return  <Button key={streamId} title={`${streamId} Toggle Audio`} onPress={() => { this.setState({ streamProperties }); }} /> 
    });
    return (
      <View style={{ flex: 1, flexDirection: 'row' }}>
        <OTSession apiKey={this.apiKey} sessionId={this.sessionId} token={this.token} eventHandlers={this.sessionEvents}>
          <OTSubscriber style={{ width: 100, height: 100 }} streamProperties={this.state.streamProperties}/>
        </OTSession>
        { allButtons }
      </View>
    );
  }
}
```

Please make sure to add the `apiKey`, `sessionId`, and `token` before you run the code.

**Comment by sunweiyang** [comment] 2018-07-10 23:47
Thanks @msach22! When I first read @mbouxin's advice 3 days ago, I tried to do the following which didn't work:
```
  _handleMute() {
      var streamProperties = this.state.streamProperties;
      for (var streamId in this.state.streamProperties) {
        streamProperties[streamId].subscribeToAudio = this.state.muted;
      }
      this.setState({
        streamProperties,
        muted: !this.state.muted
      });
  }
```

But after your example today (using `Object.keys().map()` instead of a `for` loop), I implemented the following, which worked:
```
  _handleMute() {
      var streamProperties = this.state.streamProperties;
      Object.keys(this.state.streamProperties).map(streamId => {
        const currentStream = {
          ...this.state.streamProperties[streamId],
          subscribeToAudio: this.state.muted
        };
        streamProperties = {
          ...this.state.streamProperties,
          [streamId]: currentStream
        };
      });
      this.setState({
        streamProperties,
        muted: !this.state.muted
      });
  }
```
This solves my main original problem! But I'd still like to request a simpler JS implementation for toggling subscriber audio (and video) for future users of `opentok-react-native`.

@msach22, I leave it up to you to keep this issue open to track that, or just close it if you think it's not needed. Either way, it'd be great to add your example to `opentok-react-native-samples`.

**Comment by msach22** [comment] 2018-07-10 23:54
@sunweiyang I'm happy to hear that it's working for you.  I added the array was because of multiparty, but you could simply this example if you're only working with one subscriber.

I will close this issue and open up another issue on the `opentok-react-native-samples` repo for a samples on how to use this.

**Comment by msach22** [comment] 2018-07-10 23:55
Here's the issue: https://github.com/opentok/opentok-react-native-samples/issues/11

**Closed by msach22** 2018-07-10 23:54 UTC
