### ISSUE TITLE
Unspecific OTSessionErrorDomain error code range

### ISSUE THREAD

**Issue by ythecombinator** [opentok/opentok-react-native#48] opened 2018-04-24 23:01 UTC
### A bit of context
 
In my app we have the concept of roles which is applied for constraining sessions between certain roles. For example:

- **Admins** have a list of all users and admins which they can use to enter a `1:1` room with a specific *regular use* or another *admin*.
- **Regular Users** have just an option where they can opt in use to enter a `1:1` room with an **admin**.

### The problem

When an admin calls another one, both `OTPublisher` and `OTSubscriber` work perfectly and we have a working session. Turns out that when we have a call between an user and an admin, the user cant't see the video coming from the admin–but the admin is able to do so.

Unfortunately, it's hard for me to post here more implementation details–but I'have been debugging for hours and the problem doesn't seem to be on the described logic itself; all the data that is passed to `OTSession` (`token`, `session` etc.) is fine.

**One clue** I have is that I get these logs–that are not thrown errors, btw–, on the console everytime it happens:

<img width="504" alt="captura de tela 2018-04-24 as 19 17 40" src="https://user-images.githubusercontent.com/2644563/39217904-66a19380-47f8-11e8-8f81-e4b89abf1e14.png">

I tried to find these on the source of this lib but I couldn't. I tried to find these on the native SDK for iOS but i admit I haven't even managed to find the OpenTok pod source, actually 😆. Nor I could reading the docs.

### Details

**opentok-react-native**: `0.5.0`
**iOS**: `11.2.5`, `11.2.6 ` and `11.3.x`
**iPhone**: `SE` and `X`(both simulator and real devices)

> I know it's quite hard but if you manage to have any spare time, I'd be very happy to have a call where I could better illustrate the issue.

**Comment by msach22** [comment] 2018-04-28 22:51
@ythecombinator You can find information about the errors and error codes here: 

iOS: https://tokbox.com/developer/sdks/ios/reference/Constants/OTSessionErrorCode.html
Android: https://tokbox.com/developer/sdks/android/reference/com/opentok/android/OpentokError.ErrorCode.html

**Comment by msach22** [comment] 2018-05-01 16:51
@ythecombinator I'm going to close this issue because the error descriptions and codes are available on TokBox's website! Unfortunately, I'm unable to reproduce the 1:1 issue that you're having on my end.

Please re-open with more findings and replication steps if possible! Thanks!

**Closed by msach22** 2018-05-01 16:51 UTC

**Comment by ythecombinator** [comment] 2018-05-01 19:09
@msach22, did you have time to look at the report I sent this weekend?

It makes sense closing this since I pointed to errors codes themselves but the issue still happens: should I change both titles and description focusing on the black screen part itself and reopen this one? Or open another one? I mean... I really think it's important to keep track as an issue because:

1. It's something crucial for my app to work

1. Other people might be experiencing this issue as well
