### ISSUE TITLE
Android crash app when change streamId for subscriber component

### ISSUE THREAD

**Issue by HayTran94** [opentok/opentok-react-native#324] opened 2019-08-07 10:41 UTC
# Bug Report

**Current behavior**
I want to switch to another subscriber stream but it cause the crash in Android, not in iOS.

**Steps to reproduce**
Build a component with a streamId, after that re-render with another streamId and it crash with the following error: `The specific child already has a parent. You must call removeView() on the child's parent first.`

**Example Project**
I am following the spinet to custom subscriber view, just 1 subscriber is available at a time.

```
import { OTSubscriberView } from 'opentok-react-native'

// Render method

<OTSubscriber>
  {this.renderSubscribers}
</OTSubscriber>

// Render prop function

renderSubscribers = (subscribers) => {
  return subscribers.map((streamId) => (
    <TouchableOpacity
      onPress={() => this.handleStreamPress(streamId)}
      key={streamId}
      style={subscriberWrapperStyle}
    >
      <OTSubscriberView streamId={streamId} style={subscriberStyle} />
    </TouchableOpacity>
  ));
};
```

**What is the current *bug* behavior?**
Cause crash app

**What is the expected *correct* behavior?**
It can switch to another stream correctly like in iOS.

**Relevant logs and/or screenshots**
![Screenshot_20190806-183613](https://user-images.githubusercontent.com/39950210/62616706-6ed1dd80-b93a-11e9-81ac-f01e2d67b214.png)

**Comment by BenAllenUK** [comment] 2019-08-21 15:35
I also have this issue. Which react native amd opentok Android SDK version are you using?

**Comment by HayTran94** [comment] 2019-08-21 15:46
> I also have this issue. Which react native amd opentok Android SDK version are you using?

Hello @BenAllenUK, i use react native v0.60.3 and opentok v0.12.0. I already fixed this bug, please follow the [pull request](https://github.com/opentok/opentok-react-native/pull/326) to temporary pass the issue and wait for official merged version. Hope that will help you guy!

**Comment by ggoldens** [comment] 2019-08-22 19:15
Hi @HayTran94. Can you provide more info about how to reproduce this error? 
Can you show how you're switching streams?

**Comment by ggoldens** [comment] 2019-08-23 15:29
@HayTran94 FYI I just approved your PR. Will let you know when it's released.
Thanks for your contribution!

**Comment by enricop89** [comment] 2019-09-05 16:38
Closing since https://github.com/opentok/opentok-react-native/pull/326 should fix it

**Closed by enricop89** 2019-09-05 16:38 UTC
Labels: bug
