### ISSUE TITLE
unable to hear subscriber voice

### ISSUE THREAD

**Issue by Sach-SPF** [opentok/opentok-react-native#286] opened 2019-05-17 19:12 UTC
Hello everyone !!
I'm using the opentok react-native library where my problem is that I'm unable to hear back from a subscriber...though subscriber can see the video and listen to audio from Publisher. I'm having this issue on Android/iOS both.

has anyone had this issue before? whats the solutions?

Thanks
Sachin

**Comment by niraj1997** [comment] 2019-05-22 12:52
I am also facing the same issue. For the first time, I connected to stream I able to hear both publisher and subscriber voice but I connected to stream for the second time I am not able to hear the voice of subscriber but can able to hear the voice of the publisher.

Any solutions for it?

@msach22 Please provide the solution if you have any idea on this issue.

Thanks.

**Comment by tokkozhin** [comment] 2019-05-24 19:27
Same issue!

**Comment by Panda-ref** [comment] 2019-05-25 16:30
Every OT session after first one has no sound on Subscriber with
opentok-react-native 0.10.2 and OpenTok pod 2.16.0/2.16.1 for iOS. First one works just fine. Android doesn't seem to be affected.
Downgrading to 0.10.1 and 2.15.3 pod now.

**Comment by joelpiccoli** [comment] 2019-06-04 12:44
I'm facing the exactly same issue, but didn't find any solution yet. Anyone had any luck with this?

**Comment by joelpiccoli** [comment] 2019-06-05 20:33
Hello everyone!
I've realized that my problem lies when the ios clients connect first to the Stream, in the log I found this:
```
Bridge is not set. This is probably because you've explicitly synthesized the bridge in OTSessionManager, even though it's inherited from RCTEventEmitter.'
```

**Comment by og2t** [comment] 2019-06-19 13:19
Same here. Audio is not heard, restart of the app usually solves it.

**Comment by mbouxin** [comment] 2019-06-19 19:22
@msach22 I had the same problem here. It seems that the problem is in 2.16.X SDK. Indeed, I tried using 0.10.3 version with 2.15.3 and the two last lines of Utils.swift erased and It worked

**Comment by enricop89** [comment] 2019-06-25 09:07
**[Update]**: we found a bug in the native iOS SDK from `2.16.x` so I suggest using the `2.15.3` with the two last lines of `Utils.swift` erased as @mbouxin suggested.

Once we patch the native iOS, I will patch the `react-native` library too.

**Comment by julien-meichelbeck** [comment] 2019-07-05 15:29
Hello @enricop89, do you have an ETA for this bug fix?

We had to downgrade the iOS SDK to `2.15.3` and "opentok-react-native" to `0.10.1` in production just to fix this but now we are not able to rollout a feature that requires the latest version (`subscribeToSelf`).

**Comment by enricop89** [comment] 2019-07-07 11:35
@julien-meichelbeck I will check with the team internally and get back to you as soon as possible.

**Comment by enricop89** [comment] 2019-07-10 09:48
I suggest two workarounds if you need to test the latest version of OT React Native:

1. Install `opentok-react-native: 0.11.2`, downgrade the ios SDK in the Podfile to `2.15.3` and delete the two last lines of `Utils.swift`. 

2.  Have a look at this PR: https://github.com/opentok/opentok-react-native/pull/305. Basically, the issue with the `2.16.x` iOS SDK seems linked to the publisher object which is recreated every time.

Please, consider these two as a workaround to test the library. As soon as the native iOS library is patched, I will release the opentok-react-native one.

**Comment by ggoldens** [comment] 2019-08-05 14:54
I'll close this issue since the main reason is a bug on the native SDK, so there's nothing to fix on this package. Please feel free to re-open it in case you reproduce the same issue using the next version of the SDK.

**Closed by ggoldens** 2019-08-05 14:54 UTC

**Comment by julien-meichelbeck** [comment] 2019-08-05 15:49
Well, real users are impacted, we had to downgrade our SDKs/RN packages because of this and the roadmap is shifting because this is blocking for us.

How can we keep track of the fix ?

**Comment by enricop89** [comment] 2019-09-03 15:14
FYI: iOS `2.16.2` is out: https://tokbox.com/developer/sdks/ios/release-notes.html (August 2019)

**Comment by mehulTank** [comment] 2021-04-23 16:57
I am getting the same issue if we are calling from the same platform i.e Android to Android it is working fine but if calling from ios to android then Video is displaying but the audio is not getting audio is lost.

**Comment by parthrinnvonix-hue** [comment] 2025-08-14 08:19
I'm using v2.30.2 with two separate Android apps: App A and App B, each installed on separate devices.

When App A is running in foreground and App B initiates a call:

✅ Video and audio stream correctly in both directions.

When App A is killed (not running in background) and App B initiates a call:

✅ App A receives and answers the call.

✅ Video streaming works for both sides.

✅ Audio from App A is received by App B.

❌ Audio from App B is not received by App A.

This issue only occurs when App A is launched from a killed state. If App A is already open before the call starts, everything works as expected.

can anyone got any idea this issue? 

Thanks!!
