### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by rossenv** [opentok/opentok-react-native#77] opened 2018-05-15 10:36 UTC
Hi, I'm facing the following problem with Android device. When build dev app (android studio or react-native run-andriod) the app builds and installs normally. When I try to open my view containing session, publisher and subscriber the app asks for permissions. Without touching alerts the app crashes with "Unfortunately, APP has stopped". After restarting the app everything is ok.
This is my opentok build.gradle:
```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.react:react-native:+'
    // From node_modules
    compile 'com.opentok.android:opentok-android-sdk:2.14.0'
}
```
and here is my AndroidManifest.xml:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.healthyco">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-feature android:name="android.hardware.camera" android:required="true" />
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
    <uses-feature android:name="android.hardware.microphone" android:required="true" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="true"
      android:theme="@style/AppTheme">
      <activity
        android:name=".SplashActivity"
        android:theme="@style/SplashTheme">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity
        android:name=".MainActivity"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:screenOrientation="portrait"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

Any idea where is my mistake?

**Comment by msach22** [comment] 2018-05-15 21:16
@rossenv Could you please share the JS and Android logs that you're seeing when the app crashes? Please also share the following:
 - OpenTok React Native version
 - React Native version

**Comment by rossenv** [comment] 2018-05-16 06:34
@msach22 Hi, here some more info:


**"react": "16.3.1"**
**"react-native": "0.55.3"**
**"opentok-react-native": "^0.6.2"**


and my Logcat:

```
05-16 09:27:10.789 5640-5640/com.healthyco D/ViewRootImpl: ViewPostImeInputStage processPointer 0
05-16 09:27:10.999 5640-5640/com.healthyco D/ViewRootImpl: ViewPostImeInputStage processPointer 1
05-16 09:27:11.039 5640-5981/com.healthyco W/Bundle: Key timestamp expected Double but value was a java.lang.Integer.  The default value 0.0 was returned.
05-16 09:27:11.049 5640-5981/com.healthyco W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
        at android.os.BaseBundle.getDouble(BaseBundle.java:903)
        at android.os.BaseBundle.getDouble(BaseBundle.java:885)
        at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:32)
        at com.reactnativenavigation.controllers.NavigationCommandsHandler.push(NavigationCommandsHandler.java:40)
        at com.reactnativenavigation.bridge.NavigationReactModule.push(NavigationReactModule.java:182)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:158)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)
05-16 09:27:11.069 5640-5640/com.healthyco D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
05-16 09:27:11.069 5640-5980/com.healthyco I/ReactNativeJS: Running application "VideoSession" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID7","navigatorID":"navigatorID1_nav0","navigatorEventID":"screenInstanceID7_events"},"rootTag":31}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
05-16 09:27:11.389 5640-5980/com.healthyco I/ReactNativeJS: 'evt: ', 'willAppear'
05-16 09:27:11.519 5640-5981/com.healthyco I/art: Thread[24,tid=5981,Native,Thread*=0xb2ba4400,peer=0x331faee0,"mqt_native_modules"] recursive attempt to load library "/data/app/com.healthyco-1/lib/arm/libopentok.so"
05-16 09:27:11.539 5640-5986/com.healthyco W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.healthyco/shared_prefs/opentok.xml.bak
05-16 09:27:11.579 5640-5981/com.healthyco D/JVM: JVM::Initialize@[tid=5981]
    JVM::JVM@[tid=5981]
    LoadClasses
    name: org/webrtc/voiceengine/BuildInfo
    name: org/webrtc/voiceengine/WebRtcAudioManager
    name: org/webrtc/voiceengine/WebRtcAudioRecord
    name: org/webrtc/voiceengine/WebRtcAudioTrack
05-16 09:27:11.589 5640-5981/com.healthyco D/opentok: *********************** ANDROID SDK 2.14.0 ********************************
    **** Lib built on May  1 2018 at 16:04:42
    **** OpenTok Android SDK : 44743ddaf2d91aa68ce491864269c34e76a4c548
    **** Copyright 2018 TokBox, Inc.
    **** Licensed under the Apache License, Version 2.0
    ************************************************************************
05-16 09:27:11.669 5640-5980/com.healthyco I/ReactNativeJS: 'evt: ', 'didAppear'
05-16 09:27:11.709 5640-5640/com.healthyco D/SensorManager: unregisterListener ::   
05-16 09:27:12.349 5640-5640/com.healthyco V/ActivityThread: updateVisibility : ActivityRecord{3134f6a token=android.os.BinderProxy@b4a1566 {com.healthyco/com.reactnativenavigation.controllers.NavigationActivity}} show : true
05-16 09:27:13.229 5640-5640/com.healthyco W/AudioCapabilities: Unsupported mime audio/mpeg-L1
    Unsupported mime audio/mpeg-L2
    Unsupported mime audio/x-ms-wma
05-16 09:27:13.239 5640-5640/com.healthyco W/AudioCapabilities: Unsupported mime audio/x-ima
    Unsupported mime audio/evrc
    Unsupported mime audio/qcelp
05-16 09:27:13.239 5640-5640/com.healthyco W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
05-16 09:27:13.259 5640-5640/com.healthyco W/AudioCapabilities: Unsupported mime audio/amr-wb-plus
    Unsupported mime audio/qcelp
    Unsupported mime audio/evrc
05-16 09:27:13.279 5640-5640/com.healthyco W/VideoCapabilities: Unsupported mime video/wvc1
05-16 09:27:13.289 5640-5640/com.healthyco W/VideoCapabilities: Unsupported mime video/x-ms-wmv
05-16 09:27:13.309 5640-5640/com.healthyco W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
05-16 09:27:13.319 5640-5640/com.healthyco W/VideoCapabilities: Unsupported mime video/wvc1
    Unsupported mime video/x-ms-wmv
05-16 09:27:13.329 5640-5640/com.healthyco W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
    Unsupported mime video/x-ms-wmv8
    Unsupported mime video/mp43
05-16 09:27:13.359 5640-5640/com.healthyco I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
05-16 09:27:13.389 5640-5640/com.healthyco W/VideoCapabilities: Unsupported mime video/sorenson
    Unrecognized profile 2130706433 for video/avc
05-16 09:27:13.399 5640-5640/com.healthyco I/OTRN: onConnected: Connected to session: 1_MX40NjExNzY1Mn5-MTUyNjA0ODcxMTY5N34xT2MrdGtOQ0xOSDZDczZjTUgxZXAreFV-fg
05-16 09:27:13.479 5640-5640/com.healthyco E/unknown:ViewManager: Error while updating prop publisherId
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:232)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:815)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:886)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.opentok.android.Publisher.setStyle(java.lang.String, java.lang.String)' on a null object reference
        at com.opentokreactnative.OTPublisherLayout.createPublisherView(OTPublisherLayout.java:29)
        at com.opentokreactnative.OTPublisherViewManager.setPublisherId(OTPublisherViewManager.java:31)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:232) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152) 
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:815) 
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928) 
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46) 
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:886) 
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7224) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
05-16 09:27:13.479 5640-5640/com.healthyco D/AndroidRuntime: Shutting down VM
05-16 09:27:13.479 5640-5640/com.healthyco E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.healthyco, PID: 5640
    com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'publisherId' of a view managed by: OTPublisherViewManager
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:92)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:232)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:815)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:886)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:232) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152) 
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:815) 
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928) 
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46) 
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:886) 
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7224) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.opentok.android.Publisher.setStyle(java.lang.String, java.lang.String)' on a null object reference
        at com.opentokreactnative.OTPublisherLayout.createPublisherView(OTPublisherLayout.java:29)
        at com.opentokreactnative.OTPublisherViewManager.setPublisherId(OTPublisherViewManager.java:31)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:232) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152) 
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:815) 
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928) 
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46) 
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:886) 
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7224) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

**Comment by msach22** [comment] 2018-05-16 17:07
@rossenv I just created a fresh application and used the `0.6.2` package and can't seem to reproduce this error. Can you please share the following?
- Device & API Level
- Sample code that you're using

**Comment by rossenv** [comment] 2018-05-29 11:28
Device: Galaxy J5
```
android {
    compileSdkVersion 26
    buildToolsVersion '26.0.1'

    defaultConfig {
        applicationId "com.myapp"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

```
dependencies {
    compile project(':react-native-linear-gradient')
    compile project(':opentok-react-native')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'
    // From node_modules
    compile project(':react-native-navigation')
}
```
```
const VideoSessionContainer = styled(OTSession)`
  flex: 1;
  width: 100%;
`;
const VideoSessionPublisher = styled(OTPublisher)`
  border-width: 1;
  border-color: #fff;
  border-radius: 5;
  height: 100;
  width: 100;
`;
const VideoSessionSubscriber = styled(OTSubscriber)`
  background-color: #999999;
  height: ${deviceHeight};
  width: 100%;
  z-index: 100;
`;

.....
// render

        <VideoSessionContainer
          apiKey={config.TOKBOX_API_KEY}
          sessionId={sessionId}
          token={token}
        >
          <VideoSessionSubscriber />
          <VideoSessionPublisher
              properties={{
                publishVideo: this.state.isPublishVideo,
                publishAudio: this.state.isPublishAudio,
                cameraPosition: this.state.cameraPosition,
              }}
            />
      </VideoSessionContainer>
```

**Comment by msach22** [comment] 2018-05-30 00:52
@rossenv Could you please update to the `0.6.4` package and see if this still happens? Please also make sure to `Invalidate Caches/Restart` in your Android Studio.

- Manik

**Comment by msach22** [comment] 2018-05-31 20:56
@rossenv Unfortunately, I'm unable to reproduce this issue with the latest packages (`0.6.4`/`0.6.5`) so I'm going to close this issue. Please re-open if this issue still exists.

**Closed by msach22** 2018-05-31 20:56 UTC

**Comment by Taras-Tymchiy** [comment] 2018-11-20 21:56
Had the same issue on detached expo app (v28).
The problem was that on some android devices the camera access permission dialog wasn't shown. Implementing PermissionAwareActivity interface in the MainActivity class (like here expo/expo#784 (comment)) worked for me

**Comment by rossenv** [comment] 2018-11-21 06:50
Thanks @Taras-Tymchiy  I'll give it a try
