### ISSUE TITLE
Android overlays issue

### ISSUE THREAD

**Issue by ConnorBarnhill** [opentok/opentok-react-native#169] opened 2018-09-14 03:29 UTC
# Bug Report

**Current behavior**
> Thanks for the update in v0.8.4 to support overlapping screens. I noticed inconsistent behavior when I tried to implement overlapping publisher and subscriber views along with touchables that have a zIndex. The touchables overlay correctly when the subscriber is connected, however they don't overlay correctly when it's just the publisher.

**Steps to reproduce**
> Include touchable opacities along with subscriber and publisher

**Example Project**
> 
```
             <View
                style={{
                  backgroundColor: "black",
                  height: "100%",
                  width: "100%"
                }}
              >
                <OTSession
                  apiKey={this.apiKey}
                  sessionId={this.sessionId}
                  token={this.token}
                >
                  <OTPublisher
                    style={{
                      position: "absolute",
                      zIndex: 1,
                      bottom: subscriberConnected ? 10 : 0,
                      left: subscriberConnected ? "66%" : 0,
                      marginLeft: -10,
                      width: publisherWidth,
                      height: publisherHeight
                    }}
                  />
                  <OTSubscriber
                    style={{
                      position: "absolute",
                      zIndex: 0,
                      bottom: 0,
                      left: 0,
                      width: subscriberWidth,
                      height: subscriberHeight
                    }}
                  />
                </OTSession>
                <TouchableOpacity
                  style={{
                    position: "absolute",
                    zindex: 2,
                    left: "10%",
                    bottom: 10,
                    marginLeft: -25
                  }}
                  onPress={() => navigation.goBack()}
                >
                  <Icon
                    name="ios-close-circle"
                    backgroundColor="transparent"
                    color="#FFFFFF"
                    size={50}
                  />
                </TouchableOpacity>
                <TouchableOpacity
                  style={{
                    position: "absolute",
                    zindex: 2,
                    left: "25%",
                    bottom: 10,
                    marginLeft: -20
                  }}
                  onPress={() => this.togglePublishAudio()}
                >
                  <Icon
                    name="ios-mic-off"
                    backgroundColor="transparent"
                    color="#FFFFFF"
                    size={50}
                  />
                </TouchableOpacity>
                <TouchableOpacity
                  style={{
                    position: "absolute",
                    zindex: 2,
                    left: "40%",
                    bottom: 10,
                    marginLeft: -25
                  }}
                  onPress={() => this.toggleCamera()}
                >
                  <Icon
                    name="ios-reverse-camera"
                    backgroundColor="transparent"
                    color="#FFFFFF"
                    size={50}
                  />
                </TouchableOpacity>
              </View>
```

**What is the current *bug* behavior?**
> Does not render properly when only publisher is connected, but does render correctly once subscriber is connected

**What is the expected *correct* behavior?**
> Should render correctly with or without subscriber

**Relevant logs and/or screenshots**
> 
<img src="https://user-images.githubusercontent.com/7959016/45527881-7aa53600-b7a3-11e8-9c8e-cd5562e2cba7.png" width="25%" height="25%">
<img src="https://user-images.githubusercontent.com/7959016/45527890-7e38bd00-b7a3-11e8-9ab6-254884d63d02.png" width="25%" height="25%">

**Comment by ConnorBarnhill** [comment] 2018-09-19 19:18
@msach22 This might be a duplicate of https://github.com/opentok/opentok-react-native/issues/162

**Comment by msach22** [comment] 2019-04-10 00:24
Thanks for pointing it out @ConnorBarnhill. This is a duplicate of #162 and we plan on addressing it this week.

**Closed by msach22** 2019-04-10 00:24 UTC
