### ISSUE TITLE
[BUG] OTSubscriber cannot be styled correctly

### ISSUE THREAD

**Issue by akandaurov** [opentok/opentok-react-native#136] opened 2018-07-17 14:50 UTC
# Bug Report

**Current behavior**
The OTSubscriber component is rendered inside an additional view and the styles are not applied correctly:
> return &lt;View&gt;{ childrenWithStreams }&lt;/View&gt;;

**Steps to reproduce**
Style OTSubscriber component to fill the screen, e.g. &lt;OTSubscriber style={{ flex: 1}} /&gt;

**What is the current *bug* behavior?**
The subscriber has 0 size and is not displayed

**What is the expected *correct* behavior?**
The component should fill in the entire screen / top level container

**Comment by msach22** [comment] 2018-07-17 20:38
@akandaurov Thanks for reporting this! This looks like a duplicate of https://github.com/opentok/opentok-react-native/issues/121 so I'm going to go ahead and close it. Please re-open if you believe it's not the same issue.

**Closed by msach22** 2018-07-17 20:38 UTC
