### ISSUE TITLE
iOS archive/build fails: library not found for -lOpenTokReactNative

### ISSUE THREAD

**Issue by gabrielbull** [opentok/opentok-react-native#108] opened 2018-06-03 14:39 UTC
Happens on my project and a brand new project with only opentok-react-native installed.

```
ld: library not found for -lOpenTokReactNative
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Runs fine in the simulator but not on archive.

Currently fixed by going to _Taget -> Build Phases_ and adding `OpenTokReactNative` under __Target Dependencies__ and under __Link Binary With Libraries__ removing `libOpenTokReactNative.a` and re-adding it.

**Comment by gabrielbull** [comment] 2018-06-03 22:43
Yes, obviously installation is done as per the instructions. You can test this issue by doing an archive build on a project with this library installed.

**Comment by msach22** [comment] 2018-06-05 16:20
Thanks for confirming @gabrielbull! I'm also able to reproduce the issue so I'm investigating a fix. Please let me know if you come across any other issues!

**Comment by msach22** [comment] 2018-06-07 23:08
@gabrielbull After investigating further, it looks like the `react-native link` command is not linking it properly. To work around this, can you add the library as a dependency of your target under `Build Phases` of your target?

**Comment by MaFranceschi** [comment] 2018-06-08 04:17
I tried to run my react native application but I got the same problem to build it. I added the project as a dependecy just like you mentioned in the last comment but the problem remains. Please, can you tell me how to fix it? @msach22 

![nativeerror](https://user-images.githubusercontent.com/6466697/41138652-be4357c4-6ab0-11e8-9d6a-ea6352fe8ac0.png)

**Comment by gabrielbull** [comment] 2018-06-08 05:00
@MaFranceschi Your issue is unrelated. A null native module means the library is not properly linked. Try react-native unlink and follow the installation instructions again.

**Comment by msach22** [comment] 2018-06-08 15:31
@MaFranceschi Were you able to get it working after following the installation process? As @gabrielbull mentioned, this issue is tracking application archive failure. If you are still unable to get the native module on iOS, please create a new issue so we can track it separately 😄

**Comment by msach22** [comment] 2018-06-08 15:31
@gabrielbull Were you able to add it as a target dependency and get it working?

**Comment by gabrielbull** [comment] 2018-06-08 17:51
Yes, that's what I did to get it working. As mentioned in my original issue comment: 

>Currently fixed by going to Taget -> Build Phases and adding OpenTokReactNative under Target Dependencies and under Link Binary With Libraries removing libOpenTokReactNative.a and re-adding it.

**Comment by MaFranceschi** [comment] 2018-06-08 19:29
Thanks @gabrielbull @msach22 I followed the steps that you told me before and it works for me. I'd to add the project as a target dependency at the Build phases and everything is on rails. :tada:

**Comment by akandaurov** [comment] 2018-06-11 14:33
Build fails for me as well when building for Generic IOS device and works when I select iPhone 8 for example. No way to make the Archive

**Comment by msach22** [comment] 2018-06-11 15:12
@gabrielbull Yes, I'm still trying to explore a fix. I don't believe it has to do with a Podfile, but I'll investigate and update this issue as soon as possible.

@akandaurov Thanks for letting us know! I'm sorry to hear that adding to the target dependency didn't work for you. We might have to revert back to adding the files manually if there is no workaround.

**Comment by renanpupin** [comment] 2018-06-11 19:19
Same bug here after upgrading RNOT.
I tried to remove the library and link again but got the error:

error: no such file or directory:
libOpenTokReactNative.a
** ARCHIVE FAILED **

**Comment by msach22** [comment] 2018-06-11 19:28
@renanpupin Yes, the workaround is mentioned here:
```
Currently fixed by going to Taget -> Build Phases and adding OpenTokReactNative under Target Dependencies and under Link Binary With Libraries removing libOpenTokReactNative.a and re-adding it.
```

**Comment by renanpupin** [comment] 2018-06-11 19:39
@msach22 Thanks!

**Comment by snobear** [comment] 2018-06-14 02:59
I was also getting `Native module cannot be null` when trying this new install method. I had to revert back to adding the files manually to Xcode per the [old README](https://github.com/opentok/opentok-react-native/blob/43b2a6bafaa58891b4bffea0374ba5e814e85b03/README.md).

**Comment by msach22** [comment] 2018-06-14 23:41
@snobear Hmm, I'm not getting the `Native module cannot be null` error. Have you updated your Pod file to not use the `use_frameworks` flag?

Lastly, could you please share your `Link Binary with Libraries` section after you link the library using `react-native link opentok-react-native`?

**Comment by snobear** [comment] 2018-06-15 01:19
@msach22 here is my Podfile

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# make sure React pod does NOT get installed as it causes ambiguous reference issues
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

target 'MicTurn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'OpenTok'
end
``` 

Here is the `Link Binary with Libraries` section in Xcode after running `react-native link opentok-react-native`:

![Uploading Screen Shot 2018-06-14 at 9.16.47 PM.png…](link binary with libraries)

This looks strange to me: when I run `react-native link opentok-react-native` it only mentions Android:

```
$ react-native link opentok-react-native
Scanning folders for symlinks in /Uses/snobear/projects/foo/node_modules
rnpm-install info Platform 'android' module opentok-react-native is already linked
```

is that expected?

**Comment by msach22** [comment] 2018-06-15 20:28
@snobear Thanks for sharing the Pod file and Libraries image. Could you please verify that you're using the `0.7.0` library version or newer?

If you're using `0.7.0` or higher, you should be seeing the linking comment about iOS as well.

**Comment by snobear** [comment] 2018-06-18 13:30
@msach22 how can I check which version of the library I have installed? I checked `Podfile.lock` but it doesn't specify a version number. Tried clicking around under  `ios/Pods/Opentok`, but no luck.

**Comment by MaFranceschi** [comment] 2018-06-18 14:42
You can see it using the `yarn list` or `npm list` command at your terminal in the root of your project. Also you can verify the version in the `package.json` of the library at the node_modules/opentok-react-native folder. @snobear

**Comment by snobear** [comment] 2018-06-18 14:46
Ah ok, thought you meant the Pod version of OT. Heres `opentok-react-native` per yarn list:

```
$ yarn list opentok-react-native
yarn list v1.7.0
⠁ (node:42255) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ opentok-react-native@0.6.5
✨  Done in 2.50s.
```

Looks like I'm not running `0.7.0`! I'll try a fresh build with the updated version and get back to you soon.

**Comment by msach22** [comment] 2018-06-18 15:13
Thanks for helping out @MaFranceschi! @snobear We just released `0.8.0` last Friday so might want to upgrade to that one 😄

**Comment by emin93** [comment] 2018-07-13 12:18
Hi! Thank you for the great work and the frequent updates.

Currently I'm facing another issue when trying to archive:
```
error: Invalid bitcode signature
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When I remove the `libOpenTokReactNative.a` from `Link Binary With Libraries` the build succeeds. As soon as I add it again it fails with the above error. I already added OpenTokReactNative to the Target Dependencies.

**Comment by mbouxin** [comment] 2018-07-18 09:06
I have the same issue than @emin93. I found a workaround which consist in going to the OpenTokReactNative xcodeproj settings and set Enable Bitcode to NO in the Build settings.

**Comment by emin93** [comment] 2018-07-20 09:19
I can confirm the workaround works for me as well. Thank you @mbouxin. 🙂

**Comment by msach22** [comment] 2018-07-22 17:59
@mbouxin @emin93 does the bitcode change allow you to archive when using `react-native link opentok-react-native` ?

**Comment by emin93** [comment] 2018-07-23 06:56
@msach22 It's really a workaround, because every time I change something in the project settings, it says that the signature has changed and then I have to re-compile with "Enable Bitcode" set to "YES". Then switch back to "Enable Bitcode" set to "NO" and then archive. It's a pretty unreliable workaround. 😕

**Comment by emin93** [comment] 2018-07-26 09:36
@msach22 Yes I get that, but sadly it doesn't always work and that's why I think it doesn't make sense to include that change/workaround in the lib.

I'll also try out some other things and write if i find out something new.

**Comment by HaroldoTeruya** [comment] 2018-08-02 20:27
I read all the comments and I tried everything, but I am getting always "Native module cannot be null".
The only work around to me is copy all the files and paste in my project.

**Comment by msach22** [comment] 2018-08-06 23:49
Hey Folks, 

My sincere apologies for the delay, but I think I've discovered the fix for the library to work as expected:

Under `Build Settings` for the OpenTok React Native library target, go to `Strip Debug Symbols During Copy` and set Release to `Yes`. That should get the app to compile and archive as expected. You do not need to modify bit code settings for the app or the library.

Please let me know if you have any questions! Please also give this comment a thumbs up if it works for you so I can release this in the near future!

**Comment by msach22** [comment] 2018-08-06 23:50
@HaroldoTeruya Is this happening for a specific device on the simulator?

**Comment by HaroldoTeruya** [comment] 2018-08-07 00:07
Thank you @msach22 for your efforts! I'll try this later and give a feedback for sure.

**Comment by emin93** [comment] 2018-08-08 07:39
@msach22 No worries, I'm also on it, but currently I'm running out of ideas.

Yes, my app target has `Enable Bitcode` set to `Yes`.

**Comment by msach22** [comment] 2019-01-03 21:37
@emin93 Sorry for dropping the ball on this one, were you able to get it resolved? Is this still an issue for you?

To the other folks, is there any new information that would help resolve this?

**Comment by emin93** [comment] 2019-01-07 16:06
@msach22 Thanks for catching up and Happy New Year btw 😄

Unfortuntately I didn't get to resolve it and I'm also not working on that project anymore (I left the company, so I also don't have access to it).

**Comment by msach22** [comment] 2019-01-30 00:08
Is anyone still facing this issue?

**Comment by msach22** [comment] 2019-05-10 23:03
Hey folks, I'm going to go ahead and close this issue. Please re-open if this persists.

**Closed by msach22** 2019-05-10 23:03 UTC
