### ISSUE TITLE
APP not responding after disconnect the call in Android

### ISSUE THREAD

**Issue by TarunCodiant** [opentok/opentok-react-native#304] opened 2019-06-24 11:01 UTC
Hello All,
For Android Only:
I am facing issue with opentok audio calling functionality - when i disconnect the call at that moment app goes in hang mode not responding any event and we need kill the app every time.
Could you please help me on this I am facing this issues last 3 days.

Using configrations:
opentok version - 0.11.1
RN version - 0.59.5
implementation 'com.opentok.android:opentok-android-sdk:2.16.0'

**Comment by knavu2** [comment] 2019-06-25 07:55
We've been having the same issue. In our case the crash is caused by line 644 of the `OTSessionManager.java` file in the native part of the library:

```java
printLogs("onDisconnected: Subscriber disconnected. Stream: "+subscriberKit.getStream().getStreamId());
```

Could you try commenting out this line to see if it fixes it? This bug was supposed to be fixed in 0.10.3, but apparently it wasn't.

**Comment by enricop89** [comment] 2019-06-25 08:27
I think it's related to #294. As @knavu2 said, the issue is on the `OTSessionManager.java` file. 
The problem is from the `2.16.0` Android SDK. I'm working on that.

**Comment by TarunCodiant** [comment] 2019-06-25 10:29
Hey @All, Thank you very much for the help!!!
Now I have fixed the issue for both end app hanging. just do simple steps and shoot the target..

Steps:
1. Downgrade the opentok android skd version 2.16.0 to 2.15.3
2. Updgrade the opentoke version -  0.11.1

Cheers!!!

**Comment by enricop89** [comment] 2019-06-25 10:43
Close as depending on native SDK Android. Waiting for patch.

**Closed by enricop89** 2019-06-25 10:43 UTC

**Comment by timhuff** [comment] 2019-07-25 19:57
how exactly do you perform the downgrade?

**Comment by enricop89** [comment] 2019-07-26 08:50
@timhuff you open the project with Android Studio, navigate to the build.gradle file and set the version

**Comment by timhuff** [comment] 2019-07-26 18:28
Ah, alright. Thanks. Wasn't sure which opentok you were referring to. This solved my issue, though. Thanks for the tip.

**Comment by AideProjet** [comment] 2019-09-27 08:33
Hello, any news for an update to fix this? Thanks!

**Comment by enricop89** [comment] 2019-09-27 09:23
@AideProjet Yes, Android SDK `2.16.2` is out!!! Please test it and let me know!

**Comment by AideProjet** [comment] 2019-09-27 11:13
Thanks man, will check and let you know, appreciate the work!

**Comment by sunweiyang** [comment] 2019-10-03 21:34
@enricop89 Android SDK 2.16.2 worked great for me! Thanks!

**Comment by tomek29k** [comment] 2019-10-18 17:20
Unfortunately the bug is still there in SDK 2.16.2, I've [logged it](https://github.com/opentok/opentok-react-native/issues/357).

**Comment by JB-CHAUVIN** [comment] 2019-11-25 16:34
Hello, any workaround to fix this ?

**Comment by msach22** [comment] 2019-11-25 16:43
Hi team, we're working on a patch for this on the Android layer. Will update as soon as we have a patch!

**Comment by palmas** [comment] 2020-06-02 11:16
The bug is still there in sdk 2.16.5(((

**Comment by palmas** [comment] 2020-06-02 11:16
> Hi team, we're working on a patch for this on the Android layer. Will update as soon as we have a patch!

Any news??
